# This is the core Meteor users collection, so we don't touch its global fields.
# Instead, we modify members of the fields subdocument:
#   fields.active: bool
#   fields.heartbeat: ts
#   fields.room_ids: [room _ids]

class @Users extends @Collection
  @collection = Meteor.users
  @fields = [
    'fields.active',
    'fields.heartbeat',
    'fields.room_ids',
  ]
  # This table is generated by Meteor and comes with a unique index on username.

  @publish: (user_id) ->
    fields = username: true, fields: true
    @find({'fields.active': true}, fields: fields)

  @heartbeat = (user_id) ->
    @update({_id: user_id},
      $set: {
        'fields.heartbeat': new Date().getTime(),
        'fields.active': true,
      },
    )

  @mark_idle_users = (timeout) ->
    idle_time = new Date().getTime() - timeout
    @update({'fields.heartbeat': $lt: idle_time},
      $set: 'fields.active': false,
    )
