class @RoomNames
  constructor: ->
    @data = RoomNames.data
    @used_set = {}
    @num_used = 0

  get_unused_name: ->
    if @num_used >= @data.length
      throw new UGLIPermissionsError "The server ran out of room names!"
    while true
      name = @data[Math.floor @data.length*(do Math.random)]
      check name, String
      if name not of @used_set
        @used_set[name] = true
        @num_used += 1
        return name

  free_name: (name) ->
    assert (name of @used_set), "Name #{name} was not in use!"
    delete @used_set[name]
    @num_used -= 1

  @data: [
    'Exterior Docking Hangar',
    'Air Lock',
    'Emergency Evacuation Area',
    'Biotech Research Area',
    'Biohazard Containment',
    'Reactor Core',
    'Reactor Core Entrance',
    'Deck Beta Conduit Hall',
    'Deck Alpha Access Hall',
    'Deck Alpha Umbilical Hall',
    'Map Facility',
    'Connection Elevator to Deck Beta',
    'Deck Beta Security Hall',
    'Deck Beta Transit Hall',
    'Cargo Freight Lift to Deck Gamma',
    'Deck Gamma Monitor Hall',
    'Subventilation Shaft',
    'Main Ventilation Shaft',
    'Connection Elevator to Deck Alpha',
    'Deck Alpha Mech Shaft',
    'Landing Site',
    'Artifact Temple',
    'Gully',
    'Life Grove',
    'Root Cave',
    'Frigate Crash Site',
    'Great Tree Hall',
    'Life Grove Tunnel',
    'Waterfall Cavern',
    'Canyon Cavern',
    'Arbor Chamber',
    'Great Tree Chamber',
    'Overgrown Cavern',
    'Transport Tunnel',
    'Temple Hall',
    'Temple Security Station',
    'Temple Lobby',
    'Root Tunnel',
    'Alcove',
    'Frigate Access Tunnel',
    'Save Station',
    'Reactor Access',
    'Hydro Access Tunnel',
    'Ruins Entrance',
    'Main Plaza',
    'Nursery Access',
    'Ruined Nursery',
    'North Atrium',
    'Ruined Gallery',
    'Map Station',
    'Totem Access',
    'Hive Totem',
    'Transport Access North',
    'Ruined Shrine Access',
    'Ruined Shrine',
    'Ruined Fountain Access',
    'Ruined Fountain',
    'Meditation Fountain',
    'Arboretum Access',
    'Arboretum',
    'Sunchamber Lobby',
    'Sunchamber Access',
    'Sunchamber',
    'Sun Tower Access',
    'Sun Tower',
    'Vault Access',
    'Vault',
    'Plaza Access',
    'Gathering Hall Access',
    'Gathering Hall',
    'Watery Hall Access',
    'Watery Hall',
    'East Atrium',
    'Energy Core Access',
    'Energy Core',
    'Burn Dome Access',
    'Burn Dome',
    'West Furnace Access',
    'Furnace',
    'Tower of Light',
    'Tower Chamber',
    'Elder Chamber',
    'Training Chamber',
    'Crossway',
    'Hall of the Elders',
    'Reflecting Pool',
    'Antechamber',
    'Magma Pool',
    'Dynamo',
    'Training Chamber Access',
    'Transport Access South',
    'Dynamo Access',
    'Tower of Light Access',
    'Crossway Access West',
    'Elder Hall Access',
    'Reflecting Pool Access',
    'Piston Tunnel',
    'Burning Trail',
    'Lake Tunnel',
    'Lava Lake',
    'Pit Tunnel',
    'Monitor Tunnel',
    'Monitor Station',
    'Warrior Shrine',
    'Shore Tunnel',
    'Fiery Shores',
    'Twin Fires Tunnel',
    'Geothermal Core',
    'Plasma Processing',
    'Twin Fires',
    'North Core Tunnel',
    'South Core Tunnel',
    'Storage Cavern',
    'Gravity Chamber',
    'Ice Ruins East',
    'Ruined Courtyard',
    'Ice Ruins West',
    'Phendrana Canyon',
    'Chapel of the Elders',
    'Control Tower',
    'Storage Cave',
    'Research Lab Hydra',
    'Observatory',
    'Research Lab Aether',
    'Research Core',
    'Frozen Pike',
    'Hunter Cave',
    'Frost Cave',
    'Quarantine Cave',
    'Quarantine Monitor',
    'Security Cave',
    'Transport Access',
    'Ice Ruins Access',
    'Plaza Walkway',
    'Ruins Entryway',
    'Temple Entryway',
    'Chapel Tunnel',
    'Canyon Entryway',
    'Courtyard Entryway',
    'Quarantine Access',
    'North Quarantine Tunnel',
    'South Quarantine Tunnel',
    'Specimen Storage',
    'Research Entrance',
    'Hydra Lab Entryway',
    'Observatory Access',
    'West Tower Entrance',
    'West Tower',
    'East Tower',
    'Aether Lab Entryway',
    'Research Core Access',
    'Pike Access',
    'Hunter Cave Access',
    'Frost Cave Access',
    'Chamber Access',
    'Upper Edge Tunnel',
    'Lower Edge Tunnel',
    'Main Quarry',
    'Elite Quarters Access',
    'Elite Quarters',
    'Elite Research',
    'Ore Processing',
    'Elite Control',
    'Ventilation Shaft',
    'Central Dynamo',
    'Omega Research',
    'Mine Security Station',
    'Fungal Hall',
    'Elevator Access',
    'Elevator',
    'Fungal Hall Access',
    'Storage Depot',
    'Research Access',
    'Elite Control Access',
    'Waste Disposal',
    'Security Access',
    'Processing Center Access',
    'Save Station Mines',
    'Quarry Access',
    'Map Station Mines',
    'Missile Station Mines',
    'Maintenance Tunnel',
    'Crater Entry Point',
    'Crater Tunnel',
    'Crater Missile Station',
    'Subchamber',
  ]
